Fixes white space issues

diff --git a/renew-certificate b/renew-certificate
--- a/renew-certificate
+++ b/renew-certificate
@@ -11,14 +11,14 @@ exp_limit=30;
 
 if [ ! -f $config_file ]; then
     echo "[ERROR] config file does not exist: $config_file"
-	exit 1;
+    exit 1;
 fi
 
 cert_file="/etc/letsencrypt/live/$domain/fullchain.pem"
 key_file="/etc/letsencrypt/live/$domain/privkey.pem"
 
 if [ ! -f $cert_file ]; then
-	echo "[ERROR] certificate file not found for domain $domain."
+    echo "[ERROR] certificate file not found for domain $domain."
 fi
 
 exp=$(date -d "`openssl x509 -in $cert_file -text -noout | grep "Not After" | cut -c 25-`" +%s)
@@ -28,26 +28,26 @@ days_exp=$(echo \( $exp - $datenow \) / 86400 | bc)
 echo "Checking expiration date for $domain..."
 
 if [ "$days_exp" -gt "$exp_limit" ]; then
-	echo "The certificate is up to date, no need for renewal ($days_exp days left)."
-	exit 0;
+    echo "The certificate is up to date, no need for renewal ($days_exp days left)."
+    exit 0;
 else
-	if [ -n "$INITIAL_RENEWAL" ]; then
-		echo "Creating certificate..."
-		$le_path/letsencrypt-auto certonly --agree-tos --renew-by-default --config $config_file
+    if [ -n "$INITIAL_RENEWAL" ]; then
+        echo "Creating certificate..."
+        $le_path/letsencrypt-auto certonly --agree-tos --renew-by-default --config $config_file
 
-		echo "Creating $combined_file with latest certs..."
-		sudo bash -c "cat /etc/letsencrypt/live/$domain/fullchain.pem /etc/letsencrypt/live/$domain/privkey.pem > $combined_file"
+        echo "Creating $combined_file with latest certs..."
+        sudo bash -c "cat /etc/letsencrypt/live/$domain/fullchain.pem /etc/letsencrypt/live/$domain/privkey.pem > $combined_file"
 
-		exit 1;
-	else
-		echo "The certificate for $domain is about to expire soon. Starting Let's Encrypt (HAProxy:$http_01_port) renewal script..."
-		$le_path/letsencrypt-auto certonly --agree-tos --renew-by-default --config $config_file --http-01-port $http_01_port
+        exit 1;
+    else
+        echo "The certificate for $domain is about to expire soon. Starting Let's Encrypt (HAProxy:$http_01_port) renewal script..."
+        $le_path/letsencrypt-auto certonly --agree-tos --renew-by-default --config $config_file --http-01-port $http_01_port
 
-		echo "Creating $combined_file with latest certs..."
-		sudo bash -c "cat /etc/letsencrypt/live/$domain/fullchain.pem /etc/letsencrypt/live/$domain/privkey.pem > $combined_file"
-	fi
-	echo "Reloading $web_service"
-	/usr/sbin/service $web_service reload
-	echo "Renewal process finished for domain $domain"
-	exit 0;
+        echo "Creating $combined_file with latest certs..."
+        sudo bash -c "cat /etc/letsencrypt/live/$domain/fullchain.pem /etc/letsencrypt/live/$domain/privkey.pem > $combined_file"
+    fi
+    echo "Reloading $web_service"
+    /usr/sbin/service $web_service reload
+    echo "Renewal process finished for domain $domain"
+    exit 0;
 fi
